version: "3.6"

services:

  resolver:
    environment:
      - "TZ=Europe/Brussels"
    image: "docker.io/alpinelinux/unbound:latest"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    # Static IP address on both interfaces because unbound doesn't support
    # interface-based binding 
    networks:
      # Link with Bind for DNS requests 
      internal-net:
        ipv4_address: 172.18.2.2
      # Receive queries from endpoints, perform DoH requests
      external-net:   
        ipv4_address: 172.17.31.10
    ports:
      - "127.0.0.1:53:53/udp"
    restart: "unless-stopped"
    volumes:
      - "/usr/share/dns/root.hints:/etc/unbound/root.hints"
      - "/etc/ssl/certs/ca-certificates.crt:/etc/unbound/ca-certificates.crt"
      - "resolver-unbound:/etc/unbound"
    working_dir: "/etc/unbound"

  auth-server:
    environment:
      - "TZ=Europe/Brussels"
    image: "docker.io/ubuntu/bind9:latest"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      # Communication with auth-parser and resolver
      internal-net:
        ipv4_address: 172.18.2.3
      # Notify and AXFR with master server
      external-net:
        ipv4_address: 172.17.31.11
    restart: "unless-stopped"
    volumes:
      - "auth-server-cache:/var/cache/bind"
      - "auth-server-etc:/etc/bind"
      - "auth-server-lib:/var/lib/bind"

  auth-receiver:
    environment:
      - "TZ=Europe/Brussels"
      - "UPLOAD_DIR=/uploads"
    image: "ghcr.io/sephiroth1395/http-server-upload:main"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      # Receive files through HTTP server
      external-net:
        ipv4_address: 172.17.31.12
    ports:
      - "127.0.0.1:8090:8080/tcp"
    restart: "unless-stopped"
    volumes:
      - "auth-receiver:/uploads"

  auth-parser:
    environment:
      - "TZ=Europe/Brussels"
    image: "ghcr.io/sephiroth1395/dns-zone-list-parser:main"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      # rndc queries to auth-server to trigger restart after zone updates
      internal-net:
        ipv4_address: 172.18.2.4
    restart: "unless-stopped"
    volumes:
      - "auth-receiver:/app/uploads"
      - "auth-server-lib:/app/zones"


volumes: 
  resolver-unbound:
  auth-receiver:
  auth-server-cache:
  auth-server-etc:
  auth-server-lib:


networks:
  internal-net:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.18.2.0/29
  external-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.31.8/29        
