services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    environment:
      - OPENAI_API_BASE_URLS=${OPENAI_API_BASE_URLS}
      - OPENAI_API_KEYS=${OPENAI_API_KEYS}
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    volumes:
      - open-webui-data:/app/backend/data
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro      
    ports:
      - 127.0.0.1:8100:8080/tcp
    networks:
      ai-tools:

volumes: 
  open-webui-data:

networks:
  ai-tools:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.41.48/28