services:
  ciso-assistant-backend:
    container_name: ciso-assistant-backend
    image: ghcr.io/intuitem/ciso-assistant-community/backend:latest
    pull_policy: always
    restart: always
    environment:
      - ALLOWED_HOSTS=ciso-assistant-backend.ciso-assistant_net,localhost,ciso-assistant.srv.ev1z.be
      - CISO_ASSISTANT_URL=https://ciso-assistant.srv.ev1z.be
      - DJANGO_DEBUG=False
      - AUTH_TOKEN_TTL=7200
    volumes:
      - db:/code/db
    networks:
      net:
      proxy:
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://ciso-assistant-backend.ciso-assistant_net:8000/api/build || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 100s

  ciso-assistant-huey:
    container_name: ciso-assistant-huey
    image: ghcr.io/intuitem/ciso-assistant-community/backend:latest
    pull_policy: always
    depends_on:
      ciso-assistant-backend:
        condition: service_healthy
    restart: always
    environment:
      - ALLOWED_HOSTS=ciso-assistant-backend,localhost
      - CISO_ASSISTANT_URL=https://ciso-assistant.srv.ev1z.be
      - DJANGO_DEBUG=False
      - AUTH_TOKEN_TTL=7200
    volumes:
      - db:/code/db
    networks:
      net:       
    entrypoint:
      - /bin/sh
      - -c
      - |
        poetry run python manage.py run_huey -w 2 --scheduler-interval 60

  ciso-assistant-frontend:
    container_name: ciso-assistant-frontend
    environment:
      - PUBLIC_BACKEND_API_URL=http://ciso-assistant-backend.ciso-assistant_net:8000/api
      - PUBLIC_BACKEND_API_EXPOSED_URL=https://ciso-assistant.srv.ev1z.be/api
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
    image: ghcr.io/intuitem/ciso-assistant-community/frontend:latest
    networks:
      net:
      proxy:  
    pull_policy: always
    depends_on:
      ciso-assistant-backend:
        condition: service_healthy

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.41.112/29
  proxy:
    name: proxy_internal
    external: true

volumes:
  db: