services:

  npm:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    environment:
      - TZ='Europe/Brussels'    
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
      - npm-logs:/var/log/nginx
    networks:
      - web
      - public

  bind:
    environment:
      - TZ='Europe/Brussels'
    hostname: "dns-bind"
    image: "docker.io/ubuntu/bind9:latest"
    networks:
      internal:
        ipv4_address: 172.17.44.4
      public:
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: unless-stopped
    volumes:
      - "bind-cache:/var/cache/bind"
      - "bind-etc:/etc/bind"
      - "bind-lib:/var/lib/bind"

  external-resolver:
    image: "docker.io/alpinelinux/unbound:latest"
    networks:
      internal:
        ipv4_address: 172.17.44.2
      public:
    restart: unless-stopped
    environment:
      - TZ='Europe/Brussels'    
    volumes:
      - "external-resolver-unbound:/etc/unbound"
      - "/usr/share/dns/root.hints:/etc/unbound/root.hints"
    working_dir: "/etc/unbound"

  pihole:
    environment:
      - FTLCONF_webserver_api_password=${PIHOLE_WEB_API_PASSWORD}
      - TZ='Europe/Brussels'
    image: "pihole/pihole:latest"
    networks:
      internal:
        ipv4_address: 172.17.44.3      
      public:
      web:
    restart: unless-stopped
    volumes:
      - "pihole-dnsmasq:/etc/dnsmasq.d"
      - "pihole-etc:/etc/pihole"
      - "pihole-lighttpd:/etc/lighttpd"

  mariadb-pdns:
    image: mariadb:11-ubi
    networks:
      db:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mariadb-pdns:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_PDNS_ROOT_PW}
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      timeout: 10s
      retries: 5

  pdns:
    image: pschiffe/pdns-mysql:${PDNS_MYSQL_TAG:-latest}
    networks:
      internal:
        ipv4_address: 172.17.44.5
      db:
      web:
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_gmysql_host=${MARIADB_PDNS_SERVER}
      - PDNS_gmysql_password=${MARIADB_PDNS_ROOT_PW}
      - PDNS_primary=yes
      - PDNS_api=yes
      - PDNS_api_key=${PDNS_API_SECRET}
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=172.17.44.0/28
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
    depends_on:
      - mariadb-pdns

  pdns-admin:
    image: pschiffe/pdns-admin
    networks:
      db:
      web:
      internal:
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_ADMIN_SQLA_DB_HOST=${MARIADB_PDNS_SERVER}
      - PDNS_ADMIN_SQLA_DB_PASSWORD=${MARIADB_PDNS_ROOT_PW}
      - PDNS_API_URL="http://dns-pdns-1.dns_internal:8081/"
      - PDNS_VERSION=4.9
      - PDNS_API_KEY=${PDNS_API_SECRET}
    depends_on:
      - mariadb-pdns
      - pdns

  phpmyadmin:
    image: phpmyadmin:5
    networks:
      db:
      web:
    volumes:
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ['CMD', 'curl', '-fsSL', 'http://127.0.0.1:80']
      timeout: 10s
      retries: 5

networks:
  internal:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.17.44.0/28
  web:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.17.44.16/28
  public:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.44.32/28
  db:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.17.44.48/28

volumes:
  bind-cache:
  bind-etc:
  bind-lib:
  external-resolver-unbound:
  pihole-dnsmasq:
  pihole-etc:
  pihole-lighttpd:
  npm-data:
  npm-letsencrypt:
  npm-logs:
  mariadb-pdns:
