services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    #ports:
    #  - 127.0.0.1:8282:80/tcp
    environment:
      TZ: 'Europe/Brussels'
    volumes:
      - wallos-db:/var/www/html/db
      - wallos-logos:/var/www/html/images/uploads/logos
    networks:
      everyday-life:
      proxy:
    restart: unless-stopped

volumes: 
  wallos-db:
  wallos-logos:

networks:
  everyday-life:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.41.96/28
  proxy:
    name: proxy_internal
    external: true               