services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    environment:
      TZ: 'Europe/Brussels'
    volumes:
      - wallos-db:/var/www/html/db
      - wallos-logos:/var/www/html/images/uploads/logos
    networks:
      everyday-life:
      proxy:
    restart: unless-stopped
  kiwix:
    command: '"*.zim"'
    environment:
      TZ: 'Europe/Brussels'    
    image: ghcr.io/kiwix/kiwix-serve
    volumes:
      - kiwix-data:/data
    networks:
      everyday-life:
      proxy:
    restart: unless-stopped      

volumes: 
  wallos-db:
  wallos-logos:
  kiwix-data:

networks:
  everyday-life:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.41.96/28
  proxy:
    name: proxy_internal
    external: true               