services:
  postgres:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Europe/Brussels
    healthcheck:
      test: pg_isready -U libretime
    networks:
      libretime:

  rabbitmq:
    image: rabbitmq:3.13-alpine
    environment:
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      TZ: Europe/Brussels
    healthcheck:
      test: nc -z 127.0.0.1 5672
    networks:
      libretime:

  playout:
    image: ghcr.io/libretime/libretime-playout:${LIBRETIME_VERSION:-latest}
    init: true
    ulimits:
      nofile: 1024
    depends_on:
      - rabbitmq
    volumes:
      - /opt/libretime/config.yml:/etc/libretime/config.yml:ro
      - libretime-playout:/app
    environment:
      LIBRETIME_GENERAL_PUBLIC_URL: http://nginx:8080
      TZ: Europe/Brussels
    networks:
      libretime:

  liquidsoap:
    image: ghcr.io/libretime/libretime-playout:${LIBRETIME_VERSION:-latest}
    command: /usr/local/bin/libretime-liquidsoap
    init: true
    ulimits:
      nofile: 1024
    ports:
      - 8001:8001
      - 8002:8002
    depends_on:
      - rabbitmq
    volumes:
      - /opt/libretime/config.yml:/etc/libretime/config.yml:ro
      - libretime-playout:/app
    environment:
      LIBRETIME_GENERAL_PUBLIC_URL: http://nginx:8080
      TZ: Europe/Brussels
    networks:
      libretime:

  analyzer:
    image: ghcr.io/libretime/libretime-analyzer:${LIBRETIME_VERSION:-latest}
    init: true
    ulimits:
      nofile: 1024
    depends_on:
      - rabbitmq
    volumes:
      - /opt/libretime/config.yml:/etc/libretime/config.yml:ro
      - libretime-storage:/srv/libretime
    environment:
      LIBRETIME_GENERAL_PUBLIC_URL: http://nginx:8080
      TZ: Europe/Brussels
    networks:
      libretime:

  worker:
    image: ghcr.io/libretime/libretime-worker:${LIBRETIME_VERSION:-latest}
    init: true
    ulimits:
      nofile: 1024
    depends_on:
      - rabbitmq
    volumes:
      - /opt/libretime/config.yml:/etc/libretime/config.yml:ro
    environment:
      LIBRETIME_GENERAL_PUBLIC_URL: http://nginx:8080
      TZ: Europe/Brussels
    networks:
      libretime:

  api:
    image: ghcr.io/libretime/libretime-api:${LIBRETIME_VERSION:-latest}
    init: true
    ulimits:
      nofile: 1024
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - /opt/libretime/config.yml:/etc/libretime/config.yml:ro
      - libretime-storage:/srv/libretime
    environment:
      TZ: Europe/Brussels
    networks:
      libretime:

  legacy:
    image: ghcr.io/libretime/libretime-legacy:${LIBRETIME_VERSION:-latest}
    init: true
    ulimits:
      nofile: 1024
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - /opt/libretime/config.yml:/etc/libretime/config.yml:ro
      - libretime-assets:/var/www/html
      - libretime-storage:/srv/libretime
    environment:
      TZ: Europe/Brussels
    networks:
      libretime:

  nginx:
    image: nginx
    ports:
      - 127.0.0.1:8280:8080/tcp
    depends_on:
      - legacy
    volumes:
      - libretime-assets:/var/www/html:ro
      - libretime-storage:/srv/libretime:ro
      - /opt/libretime/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      TZ: Europe/Brussels
    networks:
      libretime:

  icecast:
    image: ghcr.io/libretime/icecast:2.4.4
    ports:
      - 127.0.0.1:8281:8000/tcp
    environment:
      ICECAST_SOURCE_PASSWORD: ${ICECAST_SOURCE_PASSWORD}
      ICECAST_ADMIN_PASSWORD: ${ICECAST_ADMIN_PASSWORD}
      ICECAST_RELAY_PASSWORD: ${ICECAST_RELAY_PASSWORD}
      TZ: Europe/Brussels
    networks:
      libretime:

volumes:
  postgres-data:
  libretime-storage:
  libretime-assets:
  libretime-playout:

networks:
  libretime:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.42.80/28
