services:

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - deluge-config:/config
      - /srv/media/Downloads:/downloads
    ports:
      - 127.0.0.1:8112:8112/tcp
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped
    networks:
      download:

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - prowlarr-config:/config
    ports:
      - 127.0.0.1:9696:9696/tcp
    restart: unless-stopped      
    networks:
      download:
      captcha:

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Brussels
    ports:
      - 127.0.0.1:8191:8191/tcp
    restart: unless-stopped 
    networks:
      captcha:    

  mylar:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - mylar-config:/config
      - /srv/media/Comics:/comics
      - /srv/media/Downloads:/downloads
    ports:
      - 127.0.0.1:8090:8090/tcp
    restart: unless-stopped
    networks:
      download:    

volumes: 
  deluge-config:
  prowlarr-config:
  mylar-config:

networks:
  download:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.42.0/28  
  captcha:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.42.16/29          