services:

  navidrome:
    image: deluan/navidrome:latest
    ports:
      - 127.0.0.1:4533:4533/tcp
    restart: unless-stopped
    environment:
      - TZ=Europe/Brussels    
    volumes:
      - navidrome-data:/data
      - "/srv/media/Musique:/music:ro"
    networks:
      players:       

volumes: 
  navidrome-data:

networks:
  players:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.42.64/28