services:

  navidrome:
    image: deluan/navidrome:latest
    ports:
    #  - 127.0.0.1:4533:4533/tcp
      - 172.16.20.241:9533:4533/tcp   # For Home Assistant direct connection
    restart: unless-stopped
    environment:
      - TZ=Europe/Brussels    
    volumes:
      - navidrome-data:/data
      - "/srv/media/Musique:/music:ro"
    networks:
      players:
      proxy:

volumes: 
  navidrome-data:

networks:
  players:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.42.64/28
  proxy:
    name: proxy_internal
    external: true        