version: "3.6"

# ntfy.sh based on reference compose from official documentation

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=Europe/Brussels
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-config:/etc/ntfy
    ports:
      - 80:80
    healthcheck: 
        test: ["CMD-SHELL", "wget -q --tries=1 https://ntfy.srv.ev1z.be/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
    networks:
      ntfy:

volumes: 
  ntfy-cache:
  ntfy-config:

networks:
  ntfy:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.17.41.10/31  