# ntfy.sh based on reference compose from official documentation
# loki based on reference documentation

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command: [ "serve", "-c", "/etc/ntfy/server.yml" ]
    environment:
      - TZ=Europe/Brussels
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-config:/etc/ntfy
    ports:
      - "127.0.0.1:8087:80/tcp"
    healthcheck: 
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:8087/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
    networks:
      ntfy:

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "127.0.0.1:3100:3100/tcp"
#    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-config:/etc/loki
    networks:
      - grafana

#  promtail:
#    image: grafana/promtail:2.9.2
#    volumes:
#      - /var/log:/var/log
#    command: -config.file=/etc/promtail/config.yml
#    networks:
#      - grafana

#  grafana:
#    environment:
#      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#    entrypoint:
#      - sh
#      - -euc
#      - |
#        mkdir -p /etc/grafana/provisioning/datasources
#        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
#        apiVersion: 1
#        datasources:
#        - name: Loki
#          type: loki
#          access: proxy 
#          orgId: 1
#          url: http://loki:3100
#          basicAuth: false
#          isDefault: true
#          version: 1
#          editable: false
#        EOF
#        /run.sh
#    image: grafana/grafana:latest
#    ports:
#      - "3000:3000"
#    networks:
#      - loki


volumes: 
  ntfy-cache:
  ntfy-config:
  loki-config:

networks:
  ntfy:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.43.0/30
  grafana:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.43.16/29  

