# ntfy.sh based on reference compose from official documentation

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command: [ "serve", "-c", "/etc/ntfy/server.yml" ]
    environment:
      - TZ=Europe/Brussels
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-config:/etc/ntfy
    ports:
      - "127.0.0.1:8087:80/tcp"
    healthcheck: 
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:8087/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
    networks:
      ntfy:

volumes: 
  ntfy-cache:
  ntfy-config:

networks:
  ntfy:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.41.24/30  