# ntfy.sh based on reference compose from official documentation
# graylog & grafana based on reference documentation

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command: [ "serve", "-c", "/etc/ntfy/server.yml" ]
    environment:
      - TZ=Europe/Brussels
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-config:/etc/ntfy
    ports:
      - "127.0.0.1:8087:80/tcp"
    healthcheck: 
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:8087/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
    networks:
      ntfy:

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-config:/etc/grafana
      - grafana-data:/var/lib/grafana
    image: grafana/grafana:latest
    ports:
      - "127.0.0.1:3001:3000/tcp"
    networks:
      - grafana
      - graylog

  mongodb:
    image: "mongo:6.0.14"
    volumes:
      - "mongodb-data:/data/db"
    restart: "on-failure"
    networks:
      - graylog

  opensearch-graylog:
    image: "opensearchproject/opensearch:2.12.0"
    volumes:
      - /monitoring/opensearch-data:/usr/share/opensearch/data    
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
#    ulimits:
#      memlock:
#        hard: -1
#        soft: -1
#      nofile:
#        soft: 65536
#        hard: 65536
    deploy:
      resources:
        limits:
          memory: 2048m
    restart: "on-failure"
    networks:
        - graylog

  graylog:
    image: graylog/graylog:6.0
    volumes:
      - graylog-data:/usr/share/graylog/data
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=https://graylog.srv.ev1z.be:9000/
    entrypoint: /usr/bin/tini -- wait-for-it opensearch-graylog.monitoring_graylog:9200 --  /docker-entrypoint.sh
    networks:
        - graylog
    restart: always
    depends_on:
      - mongodb
      - opensearch-graylog
    ports:
      # Graylog web interface and REST API
      - 127.0.0.1:9000:9000/tcp
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

volumes: 
  ntfy-cache:
  ntfy-config:
  grafana-config:
  grafana-data:
  mongodb-data:
  graylog-data:

networks:
  ntfy:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.43.0/30
  grafana:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.43.16/29
  graylog:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.43.24/29
