services:
  it-tools:
    image: ghcr.io/corentinth/it-tools:latest
    restart: unless-stopped
    networks:
      net-tools:
      proxy:
  cyberchef:
    image: ghcr.io/gchq/cyberchef:latest
    restart: unless-stopped
    networks:
      net-tools:
      proxy:
  pswd:
    image: ghcr.io/remvze/pswd:latest
    restart: unless-stopped
    networks:
      net-tools:      
      proxy:
  openregex:
    image: sunnev/openregex
    restart: unless-stopped
    environment:
      OPENREGEX_LOG_LEVEL: ERROR
      OPENREGEX_TIMEOUT_S: 5
      GUNICORN_WORKERS: 1
      GUNICORN_THREADS: 4
    networks:
      proxy:      

networks:
  net-tools:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.41.80/28
  proxy:
    name: proxy_internal
    external: true               