# Based on reference Compose files from Paperless-ngx GitHub repo

version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      net: 

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      net: 
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 127.0.0.1:8010:8000/tcp
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /srv/export:/usr/src/paperless/export
      - /srv/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1000
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: Europe/Brussels
      PAPERLESS_URL: ${PAPERLESS_URL}
      PAPERLESS_USE_X_FORWARD_HOST: True
      PAPERLESS_USE_X_FORWARD_PORT: True
      PAPERLESS_TASK_WORKERS: ${PAPERLESS_TASK_WORKERS}
    networks:
      net:

volumes:
  data:
  media:
  pgdata:
  redisdata:

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.41.32/29    