services:
  searxng:
    container_name: searxng
    image: searxng/searxng
    restart: unless-stopped
    volumes:
      - searxng-config:/etc/searxng
    ports:
      - 127.0.0.1:8087:8080/tcp
    networks:
      searxng:
  morty:
    container_name: morty
    image: dalf/morty
    restart: unless-stopped
    environment:
      - MORTY_KEY=${MORTY_KEY}
      - MORTY_ADDRESS="0.0.0.0:3000"
    ports:
      - 127.0.0.1:8090:3000/tcp      
    networks:
      searxng:

volumes: 
  searxng-config:

networks:
  searxng:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.41.40/29